#baseURL: 'http://example.org/'
languageCode: en-us
title: MinII KB
theme: hugo-book

params:
  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection: articles

markup:
  goldmark:
    renderer:
      unsafe: true
